### ISSUE TITLE
not supported thai philipine japan font unicode

### ISSUE THREAD

**Issue by wh-sugiharto** [BinBashBanana/html-obfuscator#1]
closed case

**Comment by QuiteAFancyEmerald** [comment]
Oh?

**Comment by BinBashBanana** [comment]
It said it was their first case. They might not know when to close it. I will reopen it now, and handle it soon.

(You close it when the issue is resolved)

**Comment by BinBashBanana** [comment]
Fixed! (garbled text is now fixed as well)
